version: '3'

services:
  vault:
    image: vault
    container_name: vault
    ports:
      - "8200:8200"
    volumes:
      - ./volumes/logs:/vault/logs
      - ./volumes/file:/vault/file
      - ./vault.json:/vault/config/vault.json:ro
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json